### ISSUE TITLE
draw_linerect.py of Ch2-5

### ISSUE THREAD

**Issue by Tomitomi2002** [kujirahand/book-json-sample#1]
The code of draw_linerect.py of ch2-5 seems to have a "return" statement , which prevents the execution of draw_screen(data)]
```
with open(filename, 'r', encoding='utf-8') as fp:
    return json.load(fp) 
draw_screen(data)
```

To correct this, I believe the code should be as follows:

```
with open(filename, 'r', encoding='utf-8') as fp:
    #return json.load(fp) 
    data = json.load(fp)

draw_screen(data)
```

**Comment by kujirahand** [comment]
@Tomitomi2002 
Thank you for your kind comments.

This problem already fixed.
https://github.com/kujirahand/book-json-sample/commit/94c53cda2b123b626c7137ff23e3cf65df4b7fa1
The latest version is reflected in the repository.
